base_config:
  - configs/variance.yaml

raw_data_dir:
  - data/xxx1/raw
  - data/xxx2/raw
speakers:
  - speaker1
  - speaker2
spk_ids: []
test_prefixes:
  - wav1
  - wav2
  - wav3
  - wav4
  - wav5
dictionary: dictionaries/opencpop-extension.txt
binary_data_dir: data/xxx/binary
binarization_args:
  num_workers: 0

energy_db_min: -96.0
energy_db_max: -12.0
breathiness_db_min: -96.0
breathiness_db_max: -20.0

use_spk_id: false
num_spk: 1
predict_dur: true
predict_pitch: true
predict_energy: false
predict_breathiness: false

hidden_size: 256
dur_prediction_args:
  arch: fs2
  hidden_size: 512
  dropout: 0.1
  num_layers: 5
  kernel_size: 3
  log_offset: 1.0
  loss_type: mse
  lambda_pdur_loss: 0.3
  lambda_wdur_loss: 1.0
  lambda_sdur_loss: 3.0

use_melody_encoder: false
melody_encoder_args:
  hidden_size: 128
  enc_layers: 4
use_glide_embed: false
glide_types: [up, down]
glide_embed_scale: 11.313708498984760  # sqrt(128)

pitch_prediction_args:
  pitd_norm_min: -8.0
  pitd_norm_max: 8.0
  pitd_clip_min: -12.0
  pitd_clip_max: 12.0
  repeat_bins: 64
  residual_layers: 20
  residual_channels: 256
  dilation_cycle_length: 5  # *

variances_prediction_args:
  total_repeat_bins: 48
  residual_layers: 10
  residual_channels: 192
  dilation_cycle_length: 4  # *

lambda_dur_loss: 1.0
lambda_pitch_loss: 1.0
lambda_var_loss: 1.0

optimizer_args:
  lr: 0.0006
lr_scheduler_args:
  scheduler_cls: torch.optim.lr_scheduler.StepLR
  step_size: 12000
  gamma: 0.75
max_batch_frames: 80000
max_batch_size: 48
max_updates: 288000

num_valid_plots: 10
val_check_interval: 2000
num_ckpt_keep: 5
permanent_ckpt_start: 180000
permanent_ckpt_interval: 10000
pl_trainer_devices: 'auto'
pl_trainer_precision: '32-true'
